os: linux
dist: trusty
sudo: required

before_install:
 - sudo apt-get install -y pandoc rubber
 - sudo apt-get install -y texlive-fonts-recommended
 - sudo apt-get install -y texlive-latex-recommended texlive-latex-extra
 - sudo apt-get install -y texlive-science texlive-pictures
 - sudo apt-get install -y texlive-xetex

script:
 - sed -i 's|^\[\!\[.*||g' README.md
 - pandoc -s --from=markdown --to=latex -V geometry:letterpaper,margin=1in -o README.tex README.md
 - rubber --pdf README.tex

 - sed -i 's|^\[\!\[.*||g' LICENSE.md
 - pandoc -s --from=markdown --to=latex -V geometry:letterpaper,margin=1in -o LICENSE.tex LICENSE.md
 - rubber --pdf LICENSE.tex

 - lualatex --halt-on-error deconinck_AAPTSM16.tex

deploy:
  provider: releases
  api_key: 4a344f2e5de816460470ce427b4a8d79fc449c12
  file:
   - README.pdf
   - LICENSE.pdf
   - deconinck_AAPTSM16.pdf
  skip_cleanup: true
  overwrite: true
  on:
    repo: SmallHallMakerspace/AAPTSM16
